package com.zdf.internalcommon.constant;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * @author mrzhang
 * @description Status code
 * @date 2024/3/16 19:43
 */
@Getter
@AllArgsConstructor
public enum StatusCode {
    //成功
    SUCCESS(1, "SUCCESS"),
    FAIL(0, "FAIL"),
    TOKEN_IS_EMPTY(10001, "TOKEN IS EMPTY"),
    INSERT_USER_ERROR(10002, "INSERT USER ERROR"),
    USER_IS_NOT_EXIT(10003, "USER IS NOT EXIT"),
    UPDATE_ROLE_ERROR(10004, "UPDATE ROLE ERROR"),
    DELETE_ROLE_ERROR(10005, "DELETE ROLE ERROR"),
    COMMUNITY_NUMBER_IS_EMPTY(10006, "COMMUNITY Id IS EMPTY"),
    PHONE_NUMBER_FORMAT_IS_ERROR(10007, "PHONE NUMBER FORMAT IS ERROR"),
    DEPT_TABLE_IS_EMPTY(10008, "DEPT TABLE IS EMPTY"),
    VERIFY_CODE_HAS_EXPIRED(10009, "VERIFY_CODE_HAS_EXPIRED"),
    VERIFY_CODE_IS_ERROR(10010, "VERIFY CODE IS ERROR"),
    AUTHENTICATION_ERROR(10011, "AUTHENTICATION ERROR"),
    TOKEN_IS_ERROR(10012, "TOKEN IS ERROR"),
    TOKEN_IS_NOT_MATCH(10013, "TOKEN IS NOT MATCH"),
    TOKEN_HAS_EXPIRED(10014, "TOKEN HAS EXPIRED"),
    USER_INFO_HAS_EXPIRED(10015, "USERINFO HAS EXPIRED"),
    USER_IS_EXIST(10016, "USER IS EXIST"),
    EXCEL_IS_EMPTY(10017, "EXCEL IS EMPTY"),
    PASSWORD_IS_ERROR(10018, "PASSWORD IS ERROR");

    private final int code;
    private final String message;
}