server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 30

spring:
  application:
    name: sszx-product
  profiles:
    active: dev

logging:
  level:
    com.zdf: debug
    org.springframework: warn

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml